### ISSUE TITLE
Warning: ReactClass: You're attempting to include a mixin that is either null or not an object.

### ISSUE THREAD

**Issue by MrLoh** [lelandrichardson/react-primitives#75]
I am using react-primitives with the latest version of create-react-native-app and am getting this warning. Seems to be a common problem with other packages as well. Or am I doing something wrong?

`Warning: ReactClass: You're attempting to include a mixin that is either null or not an object. Check the mixins included by the component, as well as any mixins they include themselves. Expected object but got undefined.`

**Comment by dominicfallows** [comment]
Perhaps related to:
- https://github.com/lelandrichardson/react-primitives/issues/71
- https://github.com/airbnb/react-sketchapp/issues/104#issuecomment-313429462

**Comment by ktj** [comment]
Not working with react 15.4.x & react-native 0.42.x either.
In native TouchableMixin is not injected.

**Comment by kirkbrauer** [comment]
Has any work been done on this? I am using ```react-primitives``` with React v16 and everything is working fine, but this warning is still being thrown. Is v4.4 not yet compatible with React 16?

**Comment by matthewtsinontas** [comment]
I did some digging on this issue as I am also encountering the console warning (not stopping build but annoying to clutter the console output).

The issue stems from a missing 'Touchable Mixin' argument being passed into `src/modules/Touchable.js` from the `src/injection/react-native.js` API injection wrapper.

The fix for this bug has actually been committed into the codebase but has not been tagged into a release yet. Simply point your 'react-natives' package at [this commit](https://github.com/lelandrichardson/react-primitives/commit/50708ca4262d2938c81460a87447ddafc95b29e1) and that should remove the warning. Here is the snippet of my package.json:

```json
{
  "dependencies" : {
    "react-primitives": "github:lelandrichardson/react-primitives#a248b6a334f48a9dfc36a8703e1056d0c79c9d3d",
  }
}
```

**Comment by mathieudutour** [comment]
the new version has been released a while ago, forgot to close this
